name: Compile LaTeX
on: [push]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show
        run: ls -R
      - name: show2
        run: docker run -v ${pwd}:/ texlive/texlive-full pwd
      - name: show3
        run: docker run -v ${pwd}:/ texlive/texlive-full ls
      - name: run
        run: docker run -v ${pwd}:/ texlive/texlive-full pdflatex main.tex
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: ./main.tex
