name: Compile LaTeX
on: [push]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show
        run: ls -R
      - name: run
        run: docker run -v $GITHUB_WORKSPACE/practice-docker-pdflatex/practice-docker-pdflatex:/workdir texlive/texlive-full pdflatex main.tex
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: $GITHUB_WORKSPACE/practice-docker-pdflatex/practice-docker-pdflatex/main.tex
